USE [CARWEB]
GO

/****** Object:  Table [dbo].[CarVisisted]    Script Date: 9/7/2016 12:36:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CarVisisted](
	[DeviceId] [varchar](65) NOT NULL,
	[CarId] [int] NOT NULL,
 CONSTRAINT [PK_CarVisisted] PRIMARY KEY CLUSTERED 
(
	[DeviceId] ASC,
	[CarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


